// //Replace all even value with -3


// #include<bits/stdc++.h>
// using namespace std;
// int main() 
// {
    // vector<vector<int>>v = {{3,6,4} , {7,8,9} , {5,2,1} };
   
  
    // for(int i=0 ;i<3 ;i++){
          
    //     for(int j=0 ;j<3 ;j++)
    //     {
    //         if(v[i][j] %2==0)
    //         {
    //             v[i][j] = -3;
    //         }
    //     }
    // }
    //   for(int i=0 ;i<3 ;i++){
    //     for(int j=0 ;j<3 ;j++){
    //         cout<<v[i][j]<<" ";
    //     }
    //     cout<<endl;
    //   }  
// }